services:
  vite-react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Map Vite's default port to localhost
    volumes:
      - .:/app       # Mount the current directory to the container
      - /app/node_modules # Prevent node_modules from being overwritten
    stdin_open: true
    tty: true
